# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'DarkModeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.2.0', :inhibit_warnings => true
  pod 'Alamofire', '~> 4.9.0'
  pod 'AlamofireImage', '~> 3.5.2'
  
  # Pods for DarkModeDemo

end
